# Generated by Django 5.2.12 on 2026-05-10 19:07

import django.core.validators
import zabroad_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_posts_post_created_183a3b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/",
                validators=[
                    zabroad_backend.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"],
                        message="Only JPG, JPEG, PNG, WebP, and GIF images are allowed.",
                    ),
                ],
            ),
        ),
    ]
