# Generated by Django 5.2.14 on 2026-05-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_image_latitude_link_longitude_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventrsvp",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="eventrsvp",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventrsvp",
            name="user",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventRSVP",
        ),
    ]
