# Generated by Django 5.2.1 on 2026-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joblisting",
            old_name="salary_range",
            new_name="home_country",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="apply_link",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="visa_sponsorship",
        ),
        migrations.AddField(
            model_name="joblisting",
            name="country_flag",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="is_hot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="posted_from",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
