# Generated by Django 5.2.12 on 2026-05-02 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_joblisting_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="home_country",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="is_hot",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="jobs_joblis_is_acti_d6e072_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["home_country", "is_active"],
                name="jobs_joblis_home_co_cbf223_idx",
            ),
        ),
    ]
