# Generated by Django 5.2.1 on 2026-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_joblisting_home_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("healthcare", "Healthcare"),
                    ("hospitality", "Hospitality"),
                    ("retail", "Retail"),
                    ("construction", "Construction"),
                    ("education", "Education"),
                    ("finance", "Finance"),
                    ("transport", "Transport"),
                    ("legal", "Legal"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
