# Generated by Django 5.2.14 on 2026-05-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_joblisting_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobListing",
        ),
    ]
