[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --no-input && python manage.py collectstatic --no-input --clear && gunicorn zabroad_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60 --log-level info"
healthcheckPath = "/api/auth/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
