# Generated by Django 5.2.12 on 2026-05-10 18:42

import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventrsvp",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="savedlisting",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="eventdetail",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="housingdetail",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="marketplacedetail",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="eventdetail",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="housingdetail",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="listings/",
                validators=[listings.models.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="marketplacedetail",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrsvp",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_rsvp"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedlisting",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"), name="unique_saved_listing"
            ),
        ),
    ]
