# Generated by Django 5.2.12 on 2026-05-02 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplacelisting",
            name="home_country",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="is_hot",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="marketplace_is_acti_e91353_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["home_country", "is_active"],
                name="marketplace_home_co_a75e94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["category", "is_active"], name="marketplace_categor_e1b6f7_idx"
            ),
        ),
    ]
