# Generated by Django 5.2.14 on 2026-05-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_marketplacelisting_home_country_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarketplaceListing",
        ),
    ]
