# Generated by Django 5.2.12 on 2026-05-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "shop_type",
                    models.CharField(
                        choices=[
                            ("grocery", "Grocery Store"),
                            ("restaurant", "Restaurant"),
                            ("electronics", "Electronics"),
                            ("fashion", "Fashion & Clothing"),
                            ("pharmacy", "Pharmacy"),
                            ("bookstore", "Bookstore"),
                            ("hardware", "Hardware Store"),
                            ("beauty", "Beauty & Cosmetics"),
                            ("services", "Services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="shops/logos/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="shops/covers/"),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_open", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("furniture", "Furniture"),
                            ("clothing", "Clothing"),
                            ("food", "Food & Groceries"),
                            ("beauty", "Beauty Products"),
                            ("books", "Books"),
                            ("services", "Services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="shops/products/"
                    ),
                ),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="local_shop.localshop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="localshop",
            index=models.Index(
                fields=["city", "is_active"], name="local_shop__city_81ffa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localshop",
            index=models.Index(
                fields=["shop_type", "is_active"], name="local_shop__shop_ty_70823a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localshop",
            index=models.Index(
                fields=["country", "is_active"], name="local_shop__country_316197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(
                fields=["category", "is_available"],
                name="local_shop__categor_f93d5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(
                fields=["shop", "is_available"], name="local_shop__shop_id_7d3715_idx"
            ),
        ),
    ]
