# Generated by Django 5.2.12 on 2026-05-10 19:07

import django.core.validators
import zabroad_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localshop",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shops/covers/",
                validators=[
                    zabroad_backend.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"],
                        message="Only JPG, JPEG, PNG, WebP, and GIF images are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="localshop",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shops/logos/",
                validators=[
                    zabroad_backend.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"],
                        message="Only JPG, JPEG, PNG, WebP, and GIF images are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shopproduct",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shops/products/",
                validators=[
                    zabroad_backend.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"],
                        message="Only JPG, JPEG, PNG, WebP, and GIF images are allowed.",
                    ),
                ],
            ),
        ),
    ]
