# Generated by Django 5.2.12 on 2026-04-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.ImageField(blank=True, null=True, upload_to="chat/media/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
