# Generated by Django 5.2.12 on 2026-04-30 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttorneyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("firm", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("languages", models.CharField(blank=True, max_length=300)),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="e.g. H-1B, Asylum, Green Card",
                        max_length=300,
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Free consult · $200/hr",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("home_country", models.CharField(blank=True, max_length=100)),
                ("country_flag", models.CharField(blank=True, max_length=10)),
                ("posted_from", models.CharField(blank=True, max_length=200)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attorney_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
