# Generated by Django 5.2.12 on 2026-04-30 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(max_length=50, unique=True)),
                ("avatar_emoji", models.CharField(default="🧑\u200d💻", max_length=10)),
                (
                    "home_country",
                    models.CharField(default="Bangladesh", max_length=100),
                ),
                ("country_flag", models.CharField(default="🇧🇩", max_length=10)),
                ("lives_in", models.CharField(default="Queens, NY", max_length=100)),
                (
                    "visa_status",
                    models.CharField(
                        choices=[
                            ("OPT", "OPT"),
                            ("CPT", "CPT"),
                            ("H1B", "H-1B"),
                            ("H4", "H-4 EAD"),
                            ("L1", "L-1"),
                            ("O1", "O-1"),
                            ("GC", "Green Card"),
                            ("CITIZEN", "Citizen"),
                            ("F1", "F-1"),
                            ("ASYLUM", "Asylum"),
                            ("OTHER", "Other"),
                        ],
                        default="OPT",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
