# Generated by Django 5.2.12 on 2026-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/avatars/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/covers/"
            ),
        ),
    ]
