# Generated by Django 5.2.12 on 2026-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_avatar_profile_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
