# Generated by Django 5.2.12 on 2026-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otpverification_attempts_otpverification_verified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="lives_in",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
