# Generated by Django 5.2.12 on 2026-05-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_lives_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="visa_status",
        ),
    ]
