# Generated by Django 5.2.12 on 2026-05-10 19:07

import django.core.validators
import zabroad_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_visa_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/avatars/",
                validators=[
                    zabroad_backend.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"],
                        message="Only JPG, JPEG, PNG, WebP, and GIF images are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/covers/",
                validators=[
                    zabroad_backend.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"],
                        message="Only JPG, JPEG, PNG, WebP, and GIF images are allowed.",
                    ),
                ],
            ),
        ),
    ]
