# Generated by Django 5.2.12 on 2026-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0002_housinglisting_latitude_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="housinglisting",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="housing/"),
        ),
    ]
