# Generated by Django 5.2.12 on 2026-05-02 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0003_housinglisting_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="housinglisting",
            name="home_country",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="housinglisting",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="housinglisting",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="housinglisting",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="housing_hou_is_acti_059052_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="housinglisting",
            index=models.Index(
                fields=["home_country", "is_active"],
                name="housing_hou_home_co_89f0f5_idx",
            ),
        ),
    ]
