# Generated by Django 5.2.1 on 2026-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0004_alter_housinglisting_home_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="housinglisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("room", "Room"),
                    ("studio", "Studio"),
                    ("condo", "Condo"),
                    ("shared", "Shared Housing"),
                    ("commercial", "Commercial"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
